#!/usr/bin/env node
// Copies the Onus user guide into docs/ for the /docs section of the site.
//
//   npm run docs:sync                 # reads ../onus
//   npm run docs:sync -- path/to/onus # or ONUS_REPO=path/to/onus
//
// The guide's source is crates/onus-cli/guide/*.md in the onus repository,
// the same files `onus help <topic>` prints. Each topic becomes
// docs/<topic>/page.md with frontmatter; the topic order and summaries come
// from crates/onus-cli/src/guide.rs. Output is deterministic: running it
// twice on the same guide changes nothing.

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const site = resolve(fileURLToPath(new URL("..", import.meta.url)));
const repo = resolve(site, process.argv[2] ?? process.env.ONUS_REPO ?? "../onus");
const guideDir = join(repo, "crates/onus-cli/guide");
const guideRs = join(repo, "crates/onus-cli/src/guide.rs");
const docsDir = join(site, "docs");
const githubBlob = "https://github.com/onushq/onus/blob/main";

if (!existsSync(guideDir) || !existsSync(guideRs)) {
  console.error(`sync-docs: no Onus guide in ${repo} (pass the onus repo path or set ONUS_REPO)`);
  process.exit(1);
}

// Topic order and summaries, as `onus help` lists them.
const topics = [...readFileSync(guideRs, "utf8").matchAll(/name: "([a-z-]+)",\s*summary: "([^"]*)"/g)].map(
  ([, name, summary]) => ({ name, summary }),
);
const names = new Set(topics.map((t) => t.name));
const files = readdirSync(guideDir).filter((f) => f.endsWith(".md")).map((f) => f.slice(0, -3)).sort();
for (const f of files) {
  if (!names.has(f)) console.warn(`sync-docs: ${f}.md is not a topic in guide.rs; skipped`);
}

const icons = {
  "getting-started": "rocket",
  commands: "terminal",
  configuration: "settings",
  ci: "code",
  plugins: "code",
};

function language(lines) {
  const first = lines.find((l) => l.trim() !== "")?.trim() ?? "";
  if (/^[{[]/.test(first)) return "json";
  if (/^(```|#{2,} |\*\*[A-Za-z]|\||<!--)/.test(first)) return "md";
  if (/^(\$ |onus |curl |cargo |git |cd |npm |pnpm |npx |jq |cp |docker |brew |export |echo |# |scripts\/|\.\/)/.test(first)) return "sh";
  if (/^(- )?["']?[\w.@/-]+["']?:(\s|$)/.test(first)) {
    // Listings such as `publish: bus.publish($EVENT, ...)` look like YAML
    // but are not; real YAML here quotes its patterns.
    // GitHub Actions conditions (`if: startsWith(...)`) are YAML values.
    const unquoted = lines
      .filter((l) => !/^\s*(- )?if:/.test(l))
      .map((l) => l.replace(/"[^"]*"|'[^']*'/g, '""'));
    return unquoted.some((l) => /\w\(/.test(l)) ? "text" : "yaml";
  }
  return "text";
}

// Indented code blocks become fenced blocks; prose gets links.
function convert(text) {
  const lines = text.replace(/\r\n/g, "\n").split("\n");
  const out = [];
  let i = 0;
  let fenced = false;
  while (i < lines.length) {
    const line = lines[i];
    if (/^```/.test(line)) fenced = !fenced;
    const prevBlank = i === 0 || lines[i - 1].trim() === "";
    if (!fenced && prevBlank && /^ {4}\S/.test(line) && !/^ {4}[-*] /.test(lines[i])) {
      const block = [];
      while (i < lines.length && (/^ {4}/.test(lines[i]) || lines[i].trim() === "")) {
        block.push(lines[i].slice(4));
        i++;
      }
      while (block.length && block[block.length - 1].trim() === "") block.pop();
      const fence = block.some((l) => l.startsWith("```")) ? "````" : "```";
      out.push(fence + language(block), ...block, fence, "");
      continue;
    }
    out.push(fenced ? line : links(line));
    i++;
  }
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function links(line) {
  return line
    .replace(/`onus help ([a-z-]+)`/g, (m, topic) => (names.has(topic) ? `[${m}](/docs/${topic})` : m))
    .replace(/(?<![\w/`[])schemas\/([\w-]+\.schema\.json)/g, (m) => `[${m}](${githubBlob}/${m})`);
}

function frontmatter(fields) {
  const body = Object.entries(fields)
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => `${k}: ${typeof v === "number" ? v : JSON.stringify(v)}`)
    .join("\n");
  return `---\n${body}\n---\n\n`;
}

rmSync(docsDir, { recursive: true, force: true });
mkdirSync(docsDir, { recursive: true });

topics.forEach((topic, index) => {
  const source = readFileSync(join(guideDir, `${topic.name}.md`), "utf8");
  // "Plugins: new languages, frameworks and ..." becomes "Plugins": the
  // sidebar shows titles on one line, and the summary is the description.
  const heading = source.match(/^# (.+)$/m)?.[1].trim() ?? topic.name;
  const title = heading.split(":")[0].trim();
  const dir = join(docsDir, topic.name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, "page.md"),
    frontmatter({ order: index + 2, title, description: topic.summary, icon: icons[topic.name] }) +
      `<!-- Generated by npm run docs:sync from crates/onus-cli/guide/${topic.name}.md in onushq/onus; edit it there. -->\n\n` +
      convert(source),
  );
});

// The introduction links every topic in `onus help` order.
const intro = `${frontmatter({
  order: 1,
  title: "Introduction",
  description: "Onus turns a pull request into a short report of changes in meaning.",
  icon: "book",
})}# Introduction

Onus turns a pull request into a short report of changes in meaning: new external services, contract changes, new relationships between components, weakened tests, broken rules. Every row is computed from the code by deterministic analysis, never generated, and links to the files and lines behind it. Onus only reads files: it never installs or runs the code it analyzes.

## Install

\`\`\`sh
curl -fsSL https://onushq.com/install.sh | sh
\`\`\`

Then, in a git repository:

\`\`\`sh
onus report --base main --head HEAD
\`\`\`

Archives for macOS, Linux and Windows are on the [releases page](https://github.com/onushq/onus/releases), and the GitHub Action reports on every pull request (see [CI](/docs/ci)).

## The guide

These pages are the guide that ships inside the \`onus\` binary: \`onus help <topic>\` prints any of them in the terminal, offline.

| Topic | What it covers |
| --- | --- |
${topics.map((t) => `| [${t.name}](/docs/${t.name}) | ${t.summary} |`).join("\n")}

The source is in the [onus repository](https://github.com/onushq/onus/tree/main/crates/onus-cli/guide).
`;
writeFileSync(join(docsDir, "page.md"), intro);

console.log(`sync-docs: ${topics.length} topics from ${guideDir}`);
